[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["justin cohen <justincoh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
